[package]
name = "p2p-data-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
futures = "0.3.31"
libp2p = { version = "0.54.1", features = ["ping", "tls", "tcp", "yamux", "tokio"] }
thiserror = "2.0.8"
tokio = { version = "1.42.0", features = ["full"] }
